project:
  type: website

website:
  title: "Psicometría con R: Teoría de respuesta al ítem (TRI)"
  navbar:
    left:
      - href: index.qmd
        text: Taller
  favicon: "img/latinr-logo.png"

format:
  html:
    theme:
      - minty
      - brand

editor: visual

lang: es 
